export const EMOJI_CATEGORIES = [
  {
    key: 'recent',
    label: 'Recently used',
    icon: '\u{1F551}',
    emoji: []
  },
  {
    key: 'smileys',
    label: 'Smileys',
    icon: '\u{1F600}',
    emoji: [
      ['\u{1F600}', 'grinning', 'smile happy face'],
      ['\u{1F603}', 'smiley', 'happy joy grin'],
      ['\u{1F604}', 'smile', 'happy joy eyes'],
      ['\u{1F601}', 'grin', 'happy teeth'],
      ['\u{1F606}', 'laughing', 'lol haha satisfied'],
      ['\u{1F605}', 'sweat_smile', 'nervous relief hot'],
      ['\u{1F923}', 'rofl', 'rolling floor laughing lmao'],
      ['\u{1F602}', 'joy', 'laugh cry tears lol'],
      ['\u{1F642}', 'slight_smile', 'happy'],
      ['\u{1F643}', 'upside_down', 'silly sarcasm'],
      ['\u{1F609}', 'wink', 'flirt joke'],
      ['\u{1F60A}', 'blush', 'happy shy proud'],
      ['\u{1F607}', 'innocent', 'halo angel'],
      ['\u{1F970}', 'smiling_face_with_hearts', 'love adore crush'],
      ['\u{1F60D}', 'heart_eyes', 'love crush like'],
      ['\u{1F929}', 'star_struck', 'amazed wow excited'],
      ['\u{1F618}', 'kissing_heart', 'kiss love flirt'],
      ['\u{1F617}', 'kissing', 'kiss'],
      ['\u{1F61A}', 'kissing_closed_eyes', 'kiss love'],
      ['\u{1F60B}', 'yum', 'tongue delicious tasty'],
      ['\u{1F61B}', 'stuck_out_tongue', 'silly tease'],
      ['\u{1F61C}', 'stuck_out_tongue_wink', 'silly tease joke'],
      ['\u{1F92A}', 'zany', 'crazy wild goofy'],
      ['\u{1F61D}', 'squinting_tongue', 'silly tease'],
      ['\u{1F911}', 'money_mouth', 'rich dollar cash'],
      ['\u{1F917}', 'hugs', 'hug embrace'],
      ['\u{1F92D}', 'hand_over_mouth', 'oops giggle whoops'],
      ['\u{1F92B}', 'shushing', 'quiet secret hush'],
      ['\u{1F914}', 'thinking', 'hmm think ponder'],
      ['\u{1F910}', 'zipper_mouth', 'silence secret'],
      ['\u{1F928}', 'raised_eyebrow', 'skeptic suspicious doubt'],
      ['\u{1F610}', 'neutral_face', 'meh blank'],
      ['\u{1F611}', 'expressionless', 'blank meh'],
      ['\u{1F636}', 'no_mouth', 'silent blank'],
      ['\u{1F60F}', 'smirk', 'smug sly'],
      ['\u{1F612}', 'unamused', 'annoyed meh done'],
      ['\u{1F644}', 'roll_eyes', 'annoyed whatever'],
      ['\u{1F62C}', 'grimacing', 'awkward yikes teeth'],
      ['\u{1F925}', 'lying_face', 'liar pinocchio nose'],
      ['\u{1F60C}', 'relieved', 'calm relax content'],
      ['\u{1F614}', 'pensive', 'sad thoughtful'],
      ['\u{1F62A}', 'sleepy', 'tired bubble'],
      ['\u{1F924}', 'drooling', 'drool want'],
      ['\u{1F634}', 'sleeping', 'zzz tired bed'],
      ['\u{1F637}', 'mask', 'sick ill covid'],
      ['\u{1F912}', 'thermometer_face', 'sick fever ill'],
      ['\u{1F92E}', 'vomiting', 'sick puke gross'],
      ['\u{1F927}', 'sneezing', 'sick tissue'],
      ['\u{1F975}', 'hot_face', 'heat sweating summer'],
      ['\u{1F976}', 'cold_face', 'freezing winter ice'],
      ['\u{1F974}', 'woozy', 'drunk dizzy tipsy'],
      ['\u{1F635}', 'dizzy_face', 'dead ko knocked out'],
      ['\u{1F92F}', 'exploding_head', 'mind blown wow'],
      ['\u{1F920}', 'cowboy', 'hat yeehaw'],
      ['\u{1F973}', 'partying_face', 'party celebrate birthday'],
      ['\u{1F60E}', 'sunglasses', 'cool shades deal'],
      ['\u{1F913}', 'nerd', 'geek glasses smart'],
      ['\u{1F9D0}', 'monocle', 'inspect examine posh'],
      ['\u{1F615}', 'confused', 'unsure hmm'],
      ['\u{1F61F}', 'worried', 'concerned'],
      ['\u{1F641}', 'slight_frown', 'sad unhappy'],
      ['\u{1F62E}', 'open_mouth', 'surprised shock wow'],
      ['\u{1F62F}', 'hushed', 'surprised stunned'],
      ['\u{1F632}', 'astonished', 'shocked amazed xox'],
      ['\u{1F633}', 'flushed', 'embarrassed blush shy'],
      ['\u{1F97A}', 'pleading', 'puppy eyes beg please'],
      ['\u{1F626}', 'frowning', 'shocked sad'],
      ['\u{1F628}', 'fearful', 'scared afraid'],
      ['\u{1F630}', 'anxious', 'nervous worried sweat'],
      ['\u{1F625}', 'sad_relieved', 'disappointed phew'],
      ['\u{1F622}', 'cry', 'sad tear upset'],
      ['\u{1F62D}', 'sob', 'crying bawling sad'],
      ['\u{1F631}', 'scream', 'fear horror shocked'],
      ['\u{1F616}', 'confounded', 'frustrated'],
      ['\u{1F623}', 'persevere', 'struggle strain'],
      ['\u{1F61E}', 'disappointed', 'sad let down'],
      ['\u{1F613}', 'sweat', 'stress hot nervous'],
      ['\u{1F629}', 'weary', 'tired exhausted'],
      ['\u{1F62B}', 'tired_face', 'exhausted fed up'],
      ['\u{1F971}', 'yawning', 'tired bored sleepy'],
      ['\u{1F624}', 'triumph', 'huff steam mad'],
      ['\u{1F621}', 'rage', 'angry mad furious'],
      ['\u{1F620}', 'angry', 'mad annoyed'],
      ['\u{1F92C}', 'cursing', 'swearing symbols mad'],
      ['\u{1F608}', 'smiling_imp', 'devil evil mischief'],
      ['\u{1F47F}', 'imp', 'devil angry evil'],
      ['\u{1F480}', 'skull', 'dead death rip'],
      ['\u{1F4A9}', 'poop', 'crap turd'],
      ['\u{1F921}', 'clown', 'circus joker'],
      ['\u{1F47B}', 'ghost', 'boo spooky halloween'],
      ['\u{1F47D}', 'alien', 'ufo space'],
      ['\u{1F916}', 'robot', 'bot ai machine'],
      ['\u{1F383}', 'jack_o_lantern', 'halloween pumpkin spooky']
    ]
  },
  {
    key: 'people',
    label: 'People',
    icon: '\u{1F44D}',
    emoji: [
      ['\u{1F44D}', 'thumbsup', 'yes good approve like'],
      ['\u{1F44E}', 'thumbsdown', 'no bad disapprove dislike'],
      ['\u{1F44C}', 'ok_hand', 'perfect fine nice'],
      ['\u{1F90C}', 'pinched_fingers', 'italian chef gesture'],
      ['✌️', 'v', 'peace victory'],
      ['\u{1F91E}', 'crossed_fingers', 'luck hope wish'],
      ['\u{1F91F}', 'love_you_gesture', 'ily love'],
      ['\u{1F918}', 'metal', 'rock horns'],
      ['\u{1F919}', 'call_me', 'shaka hang loose'],
      ['\u{1F448}', 'point_left', 'direction this'],
      ['\u{1F449}', 'point_right', 'direction this'],
      ['\u{1F446}', 'point_up', 'direction above'],
      ['\u{1F447}', 'point_down', 'direction below'],
      ['\u{1F44B}', 'wave', 'hello hi bye greeting'],
      ['\u{1F91A}', 'raised_back_of_hand', 'hand'],
      ['✋', 'raised_hand', 'stop high five hand'],
      ['\u{1F596}', 'vulcan', 'spock star trek'],
      ['\u{1F44F}', 'clap', 'applause bravo well done'],
      ['\u{1F64C}', 'raised_hands', 'praise celebrate hooray'],
      ['\u{1F450}', 'open_hands', 'hug hands'],
      ['\u{1F932}', 'palms_up', 'please beg pray'],
      ['\u{1F91D}', 'handshake', 'deal agree meeting'],
      ['\u{1F64F}', 'pray', 'please thanks hope namaste'],
      ['\u{1F485}', 'nail_care', 'nails polish fabulous'],
      ['\u{1F4AA}', 'muscle', 'strong flex gains'],
      ['\u{1F440}', 'eyes', 'look watch peek sus'],
      ['\u{1F9E0}', 'brain', 'smart think big brain'],
      ['\u{1F476}', 'baby', 'child infant'],
      ['\u{1F46E}', 'police_officer', 'cop law'],
      ['\u{1F575}️', 'detective', 'spy sleuth investigate'],
      ['\u{1F477}', 'construction_worker', 'build work'],
      ['\u{1F934}', 'prince', 'royal crown'],
      ['\u{1F478}', 'princess', 'royal crown queen'],
      ['\u{1F9D9}', 'mage', 'wizard magic caster'],
      ['\u{1F9DD}', 'elf', 'fantasy'],
      ['\u{1F9DB}', 'vampire', 'dracula fangs'],
      ['\u{1F9DC}', 'merperson', 'mermaid sea'],
      ['\u{1F9DA}', 'fairy', 'wings magic'],
      ['\u{1F9B8}', 'superhero', 'hero cape'],
      ['\u{1F9B9}', 'supervillain', 'villain evil'],
      ['\u{1F483}', 'dancer', 'dance party'],
      ['\u{1F57A}', 'man_dancing', 'dance disco'],
      ['\u{1F6B6}', 'walking', 'walk stroll'],
      ['\u{1F3C3}', 'running', 'run race hurry'],
      ['\u{1F937}', 'shrug', 'idk whatever dunno'],
      ['\u{1F926}', 'facepalm', 'smh disbelief oh no'],
      ['\u{1F64B}', 'raising_hand', 'me question volunteer'],
      ['\u{1F645}', 'no_good', 'nope denied stop'],
      ['\u{1F646}', 'ok_person', 'yes correct'],
      ['\u{1F481}', 'tipping_hand', 'sassy info whatever']
    ]
  },
  {
    key: 'nature',
    label: 'Nature',
    icon: '\u{1F436}',
    emoji: [
      ['\u{1F436}', 'dog', 'puppy pet woof'],
      ['\u{1F431}', 'cat', 'kitten pet meow'],
      ['\u{1F42D}', 'mouse', 'rodent'],
      ['\u{1F439}', 'hamster', 'pet rodent'],
      ['\u{1F430}', 'rabbit', 'bunny hare'],
      ['\u{1F98A}', 'fox', 'sly'],
      ['\u{1F43B}', 'bear', 'grizzly'],
      ['\u{1F43C}', 'panda', 'bear bamboo'],
      ['\u{1F428}', 'koala', 'bear australia'],
      ['\u{1F42F}', 'tiger', 'big cat'],
      ['\u{1F981}', 'lion', 'big cat king'],
      ['\u{1F42E}', 'cow', 'moo cattle'],
      ['\u{1F437}', 'pig', 'oink pork'],
      ['\u{1F438}', 'frog', 'toad ribbit'],
      ['\u{1F435}', 'monkey', 'ape'],
      ['\u{1F648}', 'see_no_evil', 'monkey hide oops'],
      ['\u{1F649}', 'hear_no_evil', 'monkey ignore'],
      ['\u{1F64A}', 'speak_no_evil', 'monkey quiet oops'],
      ['\u{1F414}', 'chicken', 'hen bird'],
      ['\u{1F427}', 'penguin', 'bird antarctic'],
      ['\u{1F426}', 'bird', 'tweet'],
      ['\u{1F986}', 'duck', 'quack bird'],
      ['\u{1F985}', 'eagle', 'bird hawk'],
      ['\u{1F989}', 'owl', 'bird hoot night'],
      ['\u{1F987}', 'bat', 'vampire night'],
      ['\u{1F43A}', 'wolf', 'howl pack'],
      ['\u{1F417}', 'boar', 'pig tusk'],
      ['\u{1F434}', 'horse', 'pony neigh'],
      ['\u{1F984}', 'unicorn', 'magic fantasy horn'],
      ['\u{1F41D}', 'bee', 'honey buzz'],
      ['\u{1F41B}', 'bug', 'caterpillar insect'],
      ['\u{1F98B}', 'butterfly', 'insect wings'],
      ['\u{1F40C}', 'snail', 'slow slug'],
      ['\u{1F41E}', 'lady_beetle', 'ladybug insect luck'],
      ['\u{1F422}', 'turtle', 'tortoise slow'],
      ['\u{1F40D}', 'snake', 'serpent hiss'],
      ['\u{1F996}', 't_rex', 'dinosaur rawr'],
      ['\u{1F419}', 'octopus', 'sea tentacles'],
      ['\u{1F980}', 'crab', 'sea claw'],
      ['\u{1F420}', 'tropical_fish', 'sea aquarium'],
      ['\u{1F42C}', 'dolphin', 'sea flipper'],
      ['\u{1F433}', 'whale', 'sea ocean'],
      ['\u{1F988}', 'shark', 'sea jaws'],
      ['\u{1F40A}', 'crocodile', 'alligator reptile'],
      ['\u{1F418}', 'elephant', 'trunk big'],
      ['\u{1F335}', 'cactus', 'desert plant'],
      ['\u{1F332}', 'evergreen_tree', 'pine forest'],
      ['\u{1F333}', 'tree', 'forest oak'],
      ['\u{1F334}', 'palm_tree', 'beach tropical'],
      ['\u{1F340}', 'four_leaf_clover', 'luck lucky irish'],
      ['\u{1F341}', 'maple_leaf', 'autumn canada fall'],
      ['\u{1F338}', 'cherry_blossom', 'sakura spring flower'],
      ['\u{1F339}', 'rose', 'flower love red'],
      ['\u{1F33B}', 'sunflower', 'flower yellow'],
      ['\u{1F337}', 'tulip', 'flower spring'],
      ['\u{1F331}', 'seedling', 'plant sprout grow'],
      ['⭐', 'star', 'favourite gold'],
      ['\u{1F31F}', 'star2', 'glowing shine sparkle'],
      ['✨', 'sparkles', 'shiny magic clean'],
      ['⚡', 'zap', 'lightning fast thunder'],
      ['\u{1F525}', 'fire', 'lit hot flame burn'],
      ['\u{1F308}', 'rainbow', 'pride colours'],
      ['☀️', 'sun', 'sunny weather bright'],
      ['⛅', 'partly_sunny', 'weather cloud'],
      ['☁️', 'cloud', 'weather overcast'],
      ['❄️', 'snowflake', 'cold winter snow'],
      ['\u{1F30A}', 'ocean', 'wave water sea'],
      ['\u{1F319}', 'crescent_moon', 'night sleep'],
      ['\u{1F31A}', 'new_moon_face', 'moon night creepy']
    ]
  },
  {
    key: 'food',
    label: 'Food',
    icon: '\u{1F354}',
    emoji: [
      ['\u{1F34E}', 'apple', 'fruit red'],
      ['\u{1F34C}', 'banana', 'fruit yellow'],
      ['\u{1F347}', 'grapes', 'fruit wine'],
      ['\u{1F353}', 'strawberry', 'fruit berry'],
      ['\u{1F351}', 'peach', 'fruit butt'],
      ['\u{1F352}', 'cherries', 'fruit berry'],
      ['\u{1F349}', 'watermelon', 'fruit summer'],
      ['\u{1F34D}', 'pineapple', 'fruit tropical'],
      ['\u{1F951}', 'avocado', 'toast fruit'],
      ['\u{1F345}', 'tomato', 'vegetable'],
      ['\u{1F33D}', 'corn', 'maize vegetable'],
      ['\u{1F955}', 'carrot', 'vegetable orange'],
      ['\u{1F954}', 'potato', 'vegetable spud'],
      ['\u{1F35E}', 'bread', 'loaf bakery'],
      ['\u{1F950}', 'croissant', 'bakery french'],
      ['\u{1F9C0}', 'cheese', 'dairy'],
      ['\u{1F953}', 'bacon', 'pork breakfast'],
      ['\u{1F357}', 'poultry_leg', 'chicken meat drumstick'],
      ['\u{1F354}', 'hamburger', 'burger fast food'],
      ['\u{1F35F}', 'fries', 'chips fast food'],
      ['\u{1F355}', 'pizza', 'slice italian'],
      ['\u{1F32D}', 'hotdog', 'sausage fast food'],
      ['\u{1F32E}', 'taco', 'mexican'],
      ['\u{1F32F}', 'burrito', 'mexican wrap'],
      ['\u{1F35C}', 'ramen', 'noodles soup japanese'],
      ['\u{1F363}', 'sushi', 'japanese fish rice'],
      ['\u{1F364}', 'fried_shrimp', 'tempura seafood'],
      ['\u{1F371}', 'bento', 'japanese lunch box'],
      ['\u{1F35A}', 'rice', 'bowl grain'],
      ['\u{1F95F}', 'dumpling', 'gyoza potsticker'],
      ['\u{1F366}', 'ice_cream', 'dessert soft serve'],
      ['\u{1F369}', 'doughnut', 'donut dessert sweet'],
      ['\u{1F36A}', 'cookie', 'biscuit sweet'],
      ['\u{1F382}', 'birthday_cake', 'birthday candles party'],
      ['\u{1F370}', 'cake', 'dessert slice sweet'],
      ['\u{1F36B}', 'chocolate', 'candy sweet'],
      ['\u{1F36C}', 'candy', 'sweet sugar'],
      ['\u{1F37F}', 'popcorn', 'movie snack drama'],
      ['☕', 'coffee', 'tea hot drink morning'],
      ['\u{1F375}', 'tea', 'green matcha drink'],
      ['\u{1F37A}', 'beer', 'drink pub pint'],
      ['\u{1F37B}', 'beers', 'cheers drink pub'],
      ['\u{1F377}', 'wine', 'drink glass red'],
      ['\u{1F378}', 'cocktail', 'martini drink bar'],
      ['\u{1F379}', 'tropical_drink', 'cocktail holiday bar'],
      ['\u{1F942}', 'champagne', 'cheers toast celebrate'],
      ['\u{1F9CB}', 'bubble_tea', 'boba drink'],
      ['\u{1F964}', 'cup_with_straw', 'soda drink'],
      ['\u{1F37E}', 'champagne_bottle', 'celebrate party pop']
    ]
  },
  {
    key: 'activities',
    label: 'Activities',
    icon: '\u{1F3AE}',
    emoji: [
      ['⚽', 'soccer', 'football sport ball'],
      ['\u{1F3C0}', 'basketball', 'sport ball hoop'],
      ['\u{1F3C8}', 'football', 'american sport ball'],
      ['⚾', 'baseball', 'sport ball'],
      ['\u{1F3BE}', 'tennis', 'sport ball racket'],
      ['\u{1F3D0}', 'volleyball', 'sport ball'],
      ['\u{1F3B1}', '8ball', 'pool billiards magic'],
      ['\u{1F3D3}', 'ping_pong', 'table tennis sport'],
      ['\u{1F3F8}', 'badminton', 'shuttlecock sport'],
      ['⛳', 'golf', 'sport hole flag'],
      ['\u{1F3F9}', 'bow_and_arrow', 'archery aim'],
      ['\u{1F3A3}', 'fishing', 'fish rod'],
      ['\u{1F94A}', 'boxing_glove', 'fight sport punch'],
      ['\u{1F6F9}', 'skateboard', 'skate sport'],
      ['\u{1F3BF}', 'ski', 'snow winter sport'],
      ['\u{1F3C6}', 'trophy', 'win champion award'],
      ['\u{1F947}', 'first_place', 'gold medal win'],
      ['\u{1F948}', 'second_place', 'silver medal'],
      ['\u{1F949}', 'third_place', 'bronze medal'],
      ['\u{1F3AE}', 'video_game', 'gaming controller play'],
      ['\u{1F579}️', 'joystick', 'arcade retro gaming'],
      ['\u{1F3B2}', 'game_die', 'dice roll random luck'],
      ['\u{1F3B0}', 'slot_machine', 'gamble casino jackpot'],
      ['\u{1F0CF}', 'joker', 'card wild'],
      ['\u{1F004}', 'mahjong', 'tile game'],
      ['\u{1F3AF}', 'dart', 'bullseye target aim'],
      ['\u{1F3B3}', 'bowling', 'strike pins'],
      ['\u{1F3AA}', 'circus', 'tent show'],
      ['\u{1F3AD}', 'performing_arts', 'theatre masks drama'],
      ['\u{1F3A8}', 'art', 'paint palette draw'],
      ['\u{1F3A4}', 'microphone', 'sing karaoke mic'],
      ['\u{1F3A7}', 'headphones', 'music listen audio'],
      ['\u{1F3B8}', 'guitar', 'music rock band'],
      ['\u{1F3B9}', 'musical_keyboard', 'piano music'],
      ['\u{1F941}', 'drum', 'music beat'],
      ['\u{1F3BA}', 'trumpet', 'music brass'],
      ['\u{1F3BB}', 'violin', 'music strings'],
      ['\u{1F3AC}', 'clapper', 'movie film action'],
      ['\u{1F389}', 'tada', 'party celebrate hooray congrats'],
      ['\u{1F38A}', 'confetti_ball', 'party celebrate'],
      ['\u{1F388}', 'balloon', 'party birthday'],
      ['\u{1F381}', 'gift', 'present birthday reward'],
      ['\u{1F387}', 'sparkler', 'firework celebrate']
    ]
  },
  {
    key: 'travel',
    label: 'Travel',
    icon: '\u{1F680}',
    emoji: [
      ['\u{1F697}', 'car', 'drive vehicle'],
      ['\u{1F695}', 'taxi', 'cab vehicle'],
      ['\u{1F68C}', 'bus', 'vehicle transit'],
      ['\u{1F691}', 'ambulance', 'emergency medic'],
      ['\u{1F693}', 'police_car', 'emergency cop'],
      ['\u{1F692}', 'fire_engine', 'emergency truck'],
      ['\u{1F3CE}️', 'race_car', 'formula fast speed'],
      ['\u{1F6F5}', 'motor_scooter', 'moped vehicle'],
      ['\u{1F6B2}', 'bike', 'bicycle cycle'],
      ['\u{1F682}', 'train', 'steam locomotive rail'],
      ['\u{1F680}', 'rocket', 'launch space ship fast'],
      ['✈️', 'airplane', 'flight travel plane'],
      ['\u{1F6F8}', 'flying_saucer', 'ufo alien'],
      ['\u{1F681}', 'helicopter', 'chopper fly'],
      ['⛵', 'sailboat', 'boat sea yacht'],
      ['\u{1F6A2}', 'ship', 'cruise boat sea'],
      ['\u{1F5FA}️', 'map', 'world travel atlas'],
      ['\u{1F5FF}', 'moai', 'statue easter island'],
      ['\u{1F5FD}', 'statue_of_liberty', 'new york usa'],
      ['\u{1F3F0}', 'castle', 'fortress fantasy'],
      ['\u{1F3DD}️', 'desert_island', 'beach holiday'],
      ['\u{1F3D4}️', 'mountain', 'snow peak hike'],
      ['\u{1F30B}', 'volcano', 'eruption lava'],
      ['\u{1F3E0}', 'house', 'home building'],
      ['\u{1F3E2}', 'office', 'building work'],
      ['\u{1F3E5}', 'hospital', 'medic building'],
      ['\u{1F306}', 'cityscape', 'city skyline dusk'],
      ['\u{1F3A2}', 'roller_coaster', 'theme park ride'],
      ['⛲', 'fountain', 'water park'],
      ['\u{1F9ED}', 'compass', 'direction navigate'],
      ['⛺', 'tent', 'camping outdoors']
    ]
  },
  {
    key: 'objects',
    label: 'Objects',
    icon: '\u{1F4A1}',
    emoji: [
      ['⌚', 'watch', 'time wrist'],
      ['\u{1F4F1}', 'iphone', 'phone mobile smartphone'],
      ['\u{1F4BB}', 'laptop', 'computer pc work'],
      ['\u{1F5A5}️', 'desktop', 'computer pc monitor'],
      ['⌨️', 'keyboard', 'typing input'],
      ['\u{1F5A8}️', 'printer', 'print paper'],
      ['\u{1F4BE}', 'floppy_disk', 'save retro disk'],
      ['\u{1F4BF}', 'cd', 'disc music dvd'],
      ['\u{1F4F7}', 'camera', 'photo picture snap'],
      ['\u{1F4F9}', 'video_camera', 'record film'],
      ['\u{1F4FA}', 'tv', 'television watch screen'],
      ['\u{1F4FB}', 'radio', 'music broadcast'],
      ['☎️', 'telephone', 'call phone'],
      ['\u{1F50B}', 'battery', 'power charge'],
      ['\u{1F50C}', 'electric_plug', 'power socket'],
      ['\u{1F4A1}', 'bulb', 'idea light lamp'],
      ['\u{1F526}', 'flashlight', 'torch light'],
      ['\u{1F56F}️', 'candle', 'light wax'],
      ['\u{1F4D6}', 'book', 'read open lore'],
      ['\u{1F4DA}', 'books', 'read library study'],
      ['\u{1F4DD}', 'memo', 'note write list'],
      ['✏️', 'pencil', 'write draw'],
      ['\u{1F4CC}', 'pushpin', 'pin note'],
      ['\u{1F4CE}', 'paperclip', 'attach file'],
      ['✂️', 'scissors', 'cut snip'],
      ['\u{1F511}', 'key', 'lock unlock access'],
      ['\u{1F512}', 'lock', 'secure closed private'],
      ['\u{1F513}', 'unlock', 'open access'],
      ['\u{1F528}', 'hammer', 'tool build fix'],
      ['\u{1FA93}', 'axe', 'chop tool weapon'],
      ['⚔️', 'crossed_swords', 'battle fight duel'],
      ['\u{1F6E1}️', 'shield', 'defend protect tank'],
      ['\u{1F527}', 'wrench', 'tool fix spanner'],
      ['⚙️', 'gear', 'settings cog machine'],
      ['\u{1F9EA}', 'test_tube', 'science lab potion'],
      ['\u{1F52C}', 'microscope', 'science lab study'],
      ['\u{1F52D}', 'telescope', 'space stars look'],
      ['\u{1F4B0}', 'moneybag', 'cash rich gold'],
      ['\u{1F4B5}', 'dollar', 'money cash bill'],
      ['\u{1F4B3}', 'credit_card', 'pay money bank'],
      ['\u{1F48E}', 'gem', 'diamond crystal shiny'],
      ['⚖️', 'balance_scale', 'justice fair law'],
      ['\u{1F9F2}', 'magnet', 'attract pull'],
      ['\u{1F4A3}', 'bomb', 'explosive boom'],
      ['⚰️', 'coffin', 'dead funeral rip'],
      ['\u{1F6D2}', 'shopping_cart', 'trolley buy shop'],
      ['\u{1F4E6}', 'package', 'box delivery parcel'],
      ['✉️', 'envelope', 'mail letter'],
      ['\u{1F514}', 'bell', 'notification ring alert'],
      ['\u{1F515}', 'no_bell', 'mute silence'],
      ['\u{1F451}', 'crown', 'king queen royal win'],
      ['\u{1F3A9}', 'tophat', 'magic classy'],
      ['\u{1F453}', 'glasses', 'specs eyewear'],
      ['\u{1F455}', 'shirt', 'tshirt clothes'],
      ['\u{1F456}', 'jeans', 'trousers clothes'],
      ['\u{1F45F}', 'shoe', 'sneaker trainer'],
      ['\u{1F9E6}', 'socks', 'clothes feet'],
      ['\u{1F9E2}', 'billed_cap', 'hat clothes'],
      ['\u{1F484}', 'lipstick', 'makeup beauty'],
      ['\u{1F48D}', 'ring', 'engaged marry jewel']
    ]
  },
  {
    key: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emoji: [
      ['❤️', 'heart', 'love red like'],
      ['\u{1F9E1}', 'orange_heart', 'love'],
      ['\u{1F49B}', 'yellow_heart', 'love'],
      ['\u{1F49A}', 'green_heart', 'love'],
      ['\u{1F499}', 'blue_heart', 'love'],
      ['\u{1F49C}', 'purple_heart', 'love'],
      ['\u{1F5A4}', 'black_heart', 'love dark'],
      ['\u{1F90D}', 'white_heart', 'love'],
      ['\u{1F90E}', 'brown_heart', 'love'],
      ['\u{1F494}', 'broken_heart', 'sad breakup'],
      ['\u{1F495}', 'two_hearts', 'love cute'],
      ['\u{1F49E}', 'revolving_hearts', 'love'],
      ['\u{1F493}', 'heartbeat', 'love pulse'],
      ['\u{1F496}', 'sparkling_heart', 'love shiny'],
      ['\u{1F498}', 'cupid', 'love arrow valentine'],
      ['\u{1F49D}', 'gift_heart', 'love present'],
      ['\u{1F4AF}', '100', 'perfect score full agree'],
      ['\u{1F4A2}', 'anger', 'mad vein annoyed'],
      ['\u{1F4A5}', 'boom', 'explosion collision bang'],
      ['\u{1F4AB}', 'dizzy', 'stars swirl'],
      ['\u{1F4A6}', 'sweat_drops', 'water splash'],
      ['\u{1F4A8}', 'dash', 'fast wind gone'],
      ['\u{1F4AC}', 'speech_balloon', 'talk chat comment'],
      ['\u{1F4AD}', 'thought_balloon', 'think dream'],
      ['♠️', 'spades', 'cards suit'],
      ['♥️', 'hearts', 'cards suit'],
      ['♦️', 'diamonds', 'cards suit'],
      ['♣️', 'clubs', 'cards suit'],
      ['✅', 'white_check_mark', 'yes done tick correct'],
      ['✔️', 'heavy_check_mark', 'tick done yes'],
      ['❌', 'x', 'no wrong cancel cross'],
      ['➕', 'heavy_plus_sign', 'add more'],
      ['➖', 'heavy_minus_sign', 'subtract less'],
      ['❓', 'question', 'help what ask'],
      ['❗', 'exclamation', 'important alert warning'],
      ['⚠️', 'warning', 'caution danger alert'],
      ['\u{1F6AB}', 'no_entry_sign', 'forbidden banned stop'],
      ['♻️', 'recycle', 'green reuse'],
      ['\u{1F531}', 'trident', 'weapon symbol'],
      ['⚜️', 'fleur_de_lis', 'symbol royal'],
      ['⭕', 'o', 'circle correct ring'],
      ['\u{1F195}', 'new', 'fresh badge'],
      ['\u{1F193}', 'free', 'badge zero cost'],
      ['\u{1F3B5}', 'musical_note', 'music song'],
      ['\u{1F3B6}', 'notes', 'music song tune'],
      ['➡️', 'arrow_right', 'next direction'],
      ['⬅️', 'arrow_left', 'back direction'],
      ['⬆️', 'arrow_up', 'above direction'],
      ['⬇️', 'arrow_down', 'below direction'],
      ['\u{1F504}', 'arrows_counterclockwise', 'refresh repeat reload'],
      ['\u{1F51D}', 'top', 'up arrow'],
      ['\u{1F519}', 'back', 'return arrow']
    ]
  }
];

export const EMOJI_LIST = EMOJI_CATEGORIES.filter((group) => group.key !== 'recent').flatMap(
  (group) =>
    group.emoji.map(([char, code, keywords]) => ({
      char,
      code,
      category: group.key,
      terms: `${code} ${keywords}`.replace(/_/g, ' ')
    }))
);

const BY_CODE = new Map(EMOJI_LIST.map((entry) => [entry.code, entry]));

export function emojiByCode(code) {
  return BY_CODE.get(code) || null;
}

function scoreEntry(entry, query) {
  if (entry.code === query) return 0;
  if (entry.code.startsWith(query)) return 1;
  const terms = entry.terms;
  if (terms.startsWith(query)) return 2;
  if (terms.includes(` ${query}`)) return 3;
  if (terms.includes(query)) return 4;
  return -1;
}

export function searchEmoji(rawQuery, limit = 60) {
  const query = String(rawQuery || '').trim().toLowerCase().replace(/[:_]/g, ' ').replace(/\s+/g, ' ');
  if (!query) return [];
  const hits = [];
  for (const entry of EMOJI_LIST) {
    const score = scoreEntry(entry, query);
    if (score < 0) continue;
    hits.push({ entry, score });
  }
  hits.sort((a, b) => a.score - b.score);
  return hits.slice(0, limit).map((hit) => hit.entry);
}
